# Generated by Django 5.0.2 on 2024-02-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('spin_code', models.CharField(max_length=50)),
            ],
        ),
    ]
