# Generated by Django 5.0.2 on 2024-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SpinParticipant',
        ),
    ]
