# Generated by Django 5.0.2 on 2024-02-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0002_spincode_delete_spinparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spincode',
            old_name='spin_code',
            new_name='code',
        ),
    ]
