# Generated by Django 5.0.2 on 2024-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0003_rename_spin_code_spincode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedSpinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
